name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
    # manually triggered

jobs:
  build:

    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ["3.11", "3.14"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: make env
      - name: Lint with pylint
        run: make pylint
      - name: Test with pytest
        run: make test
      - name: Documentation
        run: make doc
